server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/basic
    username: postgres
    password: wcadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


greeting:
  message: Welcome to the Simple User-service.

logging:
  level:
    com.example.userservice: DEBUG

token:
  expiration_time: 86400000
  secret: user_token
