server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:C:\\\Dev\Spring_Cloud_Work\native-file-repo
        git:
          uri: https://github.com/yOneChu/spring-cloud-config-home.git
#          uri: file:C:\\\Dev\Spring_Cloud_Work\git-local-repo
#          username: [your username]
#          password: [your password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh